DROP TABLE COMMENTS CASCADE CONSTRAINTS;
DROP TABLE POST CASCADE CONSTRAINTS;

CREATE TABLE POST (
    ID NUMBER(10),
    TITLE NVARCHAR2(50),
    DESCRIPTION NVARCHAR2(250)
);

CREATE TABLE COMMENTS (
    ID NUMBER(10),
    MESSAGE NVARCHAR2(100),
    POST_ID NUMBER(10)
);

ALTER TABLE POST ADD CONSTRAINT POST_PK PRIMARY KEY (ID);

ALTER TABLE COMMENTS ADD CONSTRAINT COMMENTS_PK PRIMARY KEY (ID);
ALTER TABLE COMMENTS ADD CONSTRAINT POST_FK FOREIGN KEY (POST_ID) REFERENCES POST (ID);
