INSERT INTO POST (ID, TITLE, DESCRIPTION) VALUES (1, 'FIRST POST', 'THIS IS FIRST POST');
INSERT INTO POST (ID, TITLE, DESCRIPTION) VALUES (2, 'SECOND POST', 'THIS IS SECOND POST');

INSERT INTO COMMENTS (ID, MESSAGE, POST_ID) VALUES (1, 'THIS IS FIRST COMMENT TO THE FIRST POST', 1);